### ISSUE TITLE
E492: Not an editor command

### ISSUE THREAD

**Issue by chc273** [adilansari/dot_files#5]
I think the features you showed are nice, but I guess there are some preparation to do before run `install.sh`. If I follow your instruction in README.md, I would get tons of errors when I run vim. Most of them are like this:

"E492: Not an editor command: Bundle 'plasticboy/vim-markdown'
line   22:
E492: Not an editor command: Bundle 'Raimondi/delimitMate'
line   23:
E492: Not an editor command: Bundle 'bling/vim-airline'
line   24:
E492: Not an editor command: Bundle 'airblade/vim-gitgutter'
line   25:
E492: Not an editor command: Bundle 'majutsushi/tagbar.git'
line   26:
E492: Not an editor command: Bundle 'luochen1990/rainbow'
line   27:
E492: Not an editor command: Bundle 'derekwyatt/vim-scala'
line   42:
E185: Cannot find color scheme 'solarized'"

It would be helpful if this situation is also explained and included to reach a broader .

**Comment by adilansari** [comment]
Thanks for pointing out @chc273 . You need to install [Vundle](https://github.com/VundleVim/Vundle.vim) package manager for vim, updated Readme. Let me know if you need help or face any other issues.
